### ISSUE TITLE
Confusing load/unload usage for kpm installed modules

### ISSUE THREAD

**Issue by parasdsingh** [concierge/kpm#8]
**Tested On**
kpm 3.5 on Concierge 4.0.0-beta.1

**Steps to reproduce**
- Install a module via kpm `/kpm install slap` (module installed in directory `kpm_slap`)
- Unload the module using module's directory name `/kpm unload kpm_slap` **[FAIL]**
- Unload using module name `/kpm unload slap` **[PASS]**
- Try to load using module name `/kpm load slap` **[FAIL]**
- Try to load using module's directory name `/kpm load kpm_slap` **[PASS]**

**What happened**
`kpm` only unloads module by their module-name while for loading them back it expects the module's directory name.

**Expected behavior**
The command's behavior should be more consistent (either all directory names, or all module names)

**Comment by drkno** [comment]
Current reason why this happens: we don't want to load every single `kassy.json`, `hubot.json` or `package.json` to find out what the real module name is. I agree it is annoying though, any ideas?

**Comment by parasdsingh** [comment]
If we don't want to load all module `json` files then we could keep a local registry of all installed modules and maintain it as modules are loaded/unloaded/installed/uninstalled.

Alternatively, since load/unload status has no meaning if Concierge restarts, we could keep a record in-memory of loaded/unloaded modules.

**Comment by drkno** [comment]
I suppose it would be possible, particularly given on the first startup all modules are loaded...
Something along the lines of:
```js
const mods = exports.platform.moduleLoader.getLoadedModules();
registry.addAll(mods);
exports.platform.moduleLoader.on('load', m => registry.add(m.mod));
```
and get the module name from `mod.__descriptor.name` and the folder from `mod.__descriptor.folderPath`.

However this means that loading two modules with the same name will be a problem. We would also need to keep an fs watch in case modules were added to the directory but not loaded.

**Comment by parasdsingh** [comment]
Modules are already expected to have different names. Additionally, currently if two modules with the same name exist; unloading them would also be a problem.

**Comment by drkno** [comment]
https://github.com/concierge/kpm/commit/0f9584d3cf3489d3ec262ef0ba61b0be8ee05e28#diff-183cde294ffdb8bd451657cb0e24b498R31 should "fix" this issue - the "kpm_" prefix is no longer needed to load.
